[build]
  # This tells Netlify to look at the current folder (the root)
  publish = "."
  # This ensures Netlify doesn't try to run a build command if you don't have one
  command = ""

# This is the standard rule to fix 404 errors for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
