backend:
  name: github
  repo: jerryliampgd-create/chinese-
  branch: main

collections:
  - name: "questions"
    label: "Questions"
    files:
      - file: "questions.json"
        label: "Questions"
        name: "questions"
        fields:
          - label: "Questions"
            name: "questions"
            widget: "list"
            fields:
              - {label: "Type", name: "type", widget: "select", options: ["L", "R"]}
              - {label: "Prompt", name: "prompt", widget: "text"}
              - {label: "Explanation", name: "explanation", widget: "text"}

